### PR TITLE
Recompile browser files

### PR DESCRIPTION
**Pull request by rnevius**
The last release didn't include updated browser assets in `dist/`, so this is the result of running the build command.

### CODE REVIEW

**Comment by anichols-ht** [comment]
Oh, thanks. I need to add husky or something to just do that automatically. For now I'll do it manually though.

**Comment by anichols-ht** [comment]
Work account there. Still me though.

**Comment by tandrewnichols** [comment]
Oh . . . I didn't notice this was a PR and not an issue (🤦), so I did it manually. Sorry about that. I'm closing cause this is already merged and published in v2.5.1 (I upgraded webpack as well to get around the deprecated crypto issues in pre-node 18 versions.)

**Comment by tandrewnichols** [comment]
Oh . . . I didn't notice this was a PR and not an issue (🤦), so I did it manually. Sorry about that. I'm closing cause this is already merged and published in v2.5.1 (I upgraded webpack as well to get around the deprecated crypto issues in pre-node 18 versions.)

**Pull request closed without merging**
