### PR TITLE
Support numbers

### LINKED ISSUE #9: Numbers
How about support for numbers?

For example, 

    `You rolled ${indefinite(82)}.`

yields "You rolled a 82." when it should yield "You rolled an 82."

### PR DESCRIPTION
**Pull request by tandrewnichols**
@travishorn Thoughts on this implementation?

Fixes #9

### CODE REVIEW

**Comment by tandrewnichols** [comment]
Wow, 15 file changes . . . it's not that big actually. I just did some clean up. The important change is [lib/rules/numbers.js](https://github.com/tandrewnichols/indefinite/pull/10/files#diff-4a7d15471a161a0100dcb2a448e67dc1)

**Comment by travishorn** [comment]
I had a chance to test the branch for my application and everything works as expected. Thanks for implementing this!

**Comment by tandrewnichols** [comment]
I just had a thought about this this morning . . . there is _yet another edge case_. Any number that starts with 11 or 18 gets "an" _EXCEPT_ any number with a multiple of 3 digits: 110; 110,000; 110,000,000; etc. So . . . not quite there yet. Can you think of any other edge cases we're missing? Maybe people do the same "eighteen hundred" thing at other marks too? Do people say "eighteen hundred thousand" (or million)??? It seems like "no," but it seems good to have two people thinking about it.

**Comment by tandrewnichols** [comment]
Nm, I'm over thinking that. It's really just 11, 18, and 1100s and 1800s.

**Comment by tandrewnichols** [comment]
Ok, I think the new rules I've got are more consistent and effective. I've also added a comment cause otherwise I'll look at this in a month and not remember why the rules are the rules.

**Comment by travishorn** [comment]
Looks good. Thanks again!

**Pull request merged**
