### PR TITLE
add single letters to the list of irregulars

### PR DESCRIPTION
**Pull request by JBaczuk**
when you try to pronounce single letters, there are a lot of irregulars.

### CODE REVIEW

**Comment by tandrewnichols** [comment]
I don't see any reason this _wouldn't_ just work, but as these are kind of different from everything else that's here, could you add a test for this case? Just testing one of the letters is sufficient. I appreciate the PR, too! Thanks!

**Comment by JBaczuk** [comment]
@tandrewnichols NP, LMK if that works!

**Comment by tandrewnichols** [comment]
🤦 Sorry! I meant, test one of the irregular letters. I should've been more clear. Maybe do `f` and `u` (lol) so there's one that should be `a` and one that should be `an` (like you did).

**Comment by tandrewnichols** [comment]
@JBaczuk Published as v2.4.0

**Pull request merged**
