### PR TITLE
Add irregular word 'euro'.

### PR DESCRIPTION
**Pull request by mrseanryan**
Add the irregular words 'euro' and 'urologist'.

### CODE REVIEW

**Comment by tandrewnichols** [comment]
Thanks!

**Comment by tandrewnichols** [comment]
Published as v2.2.2

**Comment by mrseanryan** [comment]
Thanks for merging! 
Hope you don't mind, but I created a Rust version here:
https://crates.io/crates/in_definite


RegardsSean

Sent from Yahoo Mail on Android 
 
  On Sat, 21 Sep 2019 at 20:43, Andrew Nichols<notifications@github.com> wrote:   
Thanks!

**Comment by tandrewnichols** [comment]
Ha, nice!

**Pull request merged**
