### PR TITLE
Add Utah to irregular words

### LINKED ISSUE #18: Add Utah to irregular words list
Hi there, could you please add "Utah" to the irregular word list?
Thanks!

### PR DESCRIPTION
**Pull request by tandrewnichols**
Closes #18

### CODE REVIEW

**Comment by opti** [comment]
Would you mind to publish this one?

**Comment by tandrewnichols** [comment]
I was waiting for answer to this question in the issue:

> ...is there an adjective form of that? Like "A Utahnian"?

**Comment by tandrewnichols** [comment]
I found this but it seems . . . not very definitive. https://www.ksl.com/article/24207511/is-it-utahn-or-utahan

**Comment by tandrewnichols** [comment]
Published as v2.3.1

**Pull request merged**
